name = "OutlierDetectionPython"
uuid = "2449c660-d36c-460e-a68b-92ab3c865b3e"
authors = ["David Muhr <muhrdavid@gmail.com> and contributors"]
version = "0.2.2"

[deps]
OutlierDetectionInterface = "1722ece6-f894-4ffc-b6be-6ca1174e2011"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
OutlierDetectionInterface = "0.1, 0.2"
PythonCall = "0.9"
julia = "1.6"

[extras]
OutlierDetectionTest = "66620973-d34b-445b-a614-4040704cad69"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "OutlierDetectionTest"]
